const sheetBase='https://docs.google.com/spreadsheets/d/e/2PACX-1vS8qY-gHmx2pseRmx18-8U2ET5Fs8KW8CTeFDP9xV5v3aAF1fWQoRAudwxSaaGXJzm6t8TQ05dbLHOG/pub';
const gids={text:'1338367530',cities:'0',courses:'753875659',faculty:'1239199803',institutions:'1659852286'};
const citySlugs={'Luxembourg City':'luxembourg-city','The Hague':'the-hague'};
const params=new URLSearchParams(location.search);
const presentationMode=params.get('present')==='1';
document.documentElement.dataset.materialMode=presentationMode?'presentation':'carousel';
const autoplayMode=!presentationMode&&params.get('autoplay')!=='0';
const galleryUrl='https://sites.gatech.edu/gt-eu-summer/gallery/';
const galleryPhotos=[
  ['photos/past-program/2023-canal-group.jpg','Students together during the 2023 program'],
  ['photos/past-program/2023-city-group.jpg','Students exploring a European city in 2023'],
  ['photos/past-program/2023-mountain-group.jpg','Students at a mountain overlook in 2023'],
  ['photos/past-program/2024-eu-group.jpg','The 2024 group at a European Union visit'],
  ['photos/past-program/2024-bucharest-group.jpg','The 2024 group in Bucharest'],
  ['photos/past-program/2023-program-group.jpeg','The 2023 program group']
];
const facultyPhotos={'vicki-birchfield':'assets/faculty/vicki-birchfield.jpg','1f6a6f21-01fa-5e42-88d2-83a7cd378f57':'assets/faculty/carly-potz-nielsen.jpg','thomasgr':'assets/faculty/thomas-roberts.jpg','eliza-maria-markley':'assets/faculty/eliza-markley.jpg'};
const facultyPositions={'vicki-birchfield':'center 34%','1f6a6f21-01fa-5e42-88d2-83a7cd378f57':'center 30%','thomasgr':'center center','eliza-maria-markley':'center 34%'};
const fallbackText={program_title:'European Union and Global Affairs Study Abroad Program',program_term:'Summer 2027',hero_line_1:'Let Europe be',hero_line_2:'your laboratory',intro_sentence_1:'takes you to the cities and institutions shaping Europe and the world.',intro_sentence_2:'Study global affairs where they happen in',website_url:'https://inta.gatech.edu/europeglobal',website_display:'inta.gatech.edu/europeglobal'};
const qrTarget='https://inta.gatech.edu/europeglobal';
const fallbackFaculty=[{Name:'Prof. Vicki Birchfield','Program Title':'Director',Link:'https://inta.gatech.edu/people/person/vicki-birchfield'},{Name:'Prof. Carly Potz-Nielsen','Program Title':'',Link:'https://inta.gatech.edu/people/person/1f6a6f21-01fa-5e42-88d2-83a7cd378f57'},{Name:'Prof. Thomas González Roberts','Program Title':'',Link:'https://inta.gatech.edu/people/person/thomasgr'},{Name:'Dr. Eliza Markley','Program Title':'',Link:'https://inta.gatech.edu/people/person/eliza-maria-markley'}];

function parseCsv(source){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<source.length;i++){const c=source[i];if(quoted){if(c==='"'&&source[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===','){row.push(field);field=''}else if(c==='\n'){row.push(field.replace(/\r$/,''));if(row.some(v=>v.trim()))rows.push(row);row=[];field=''}else field+=c}row.push(field.replace(/\r$/,''));if(row.some(v=>v.trim()))rows.push(row);return rows}
function objects(source){const rows=parseCsv(source),headers=(rows.shift()||[]).map((v,i)=>(i?v:v.replace(/^\uFEFF/,'')).trim());return rows.map(row=>Object.fromEntries(headers.map((h,i)=>[h,(row[i]||'').trim()]))) }
async function sheet(gid){const response=await fetch(`${sheetBase}?output=csv&gid=${gid}`,{cache:'no-store'});if(!response.ok)throw Error(response.status);return objects(await response.text())}
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
function programBrand(){const brand=el('img','program-brand');brand.src='assets/branding/program-wordmark.svg?v=approved-20260928';brand.alt='EU and Global Affairs Study Abroad Program';return brand}
function presentationBrandRow(){const row=el('div','presentation-brand-row'),school=el('img','presentation-school-logo');school.src='assets/Nunnlogo.jpg';school.alt='Georgia Tech, Sam Nunn School of International Affairs';row.append(programBrand(),school);return row}
function qrImage(className,display){const qr=el('img',className);qr.src='assets/program-website-europeglobal-qr.png';qr.alt=`QR code for ${display}`;return qr}

function openingSlide(text){const slide=el('section','slide opening'),copy=el('div','opening-copy');copy.append(el('p','eyebrow',text.program_term),el('div','rule'),el('h1','',text.program_title||fallbackText.program_title));slide.append(presentationBrandRow(),copy);slide.dataset.focus='europe';return slide}
function applicationSlide(text){const slide=el('section','slide application-slide'),copy=el('div','application-copy'),url=text.website_url||fallbackText.website_url,display=text.website_display||fallbackText.website_display,link=el('a','application-link',display);link.href=url;link.target='_blank';link.rel='noreferrer';link.addEventListener('click',event=>event.stopPropagation());copy.append(el('p','eyebrow',text.program_term),el('div','rule'),el('h1','','Apply Now'),el('p','application-instruction','Visit the program website or scan the code to open it on your phone.'),link);slide.append(presentationBrandRow(),copy);if(url===qrTarget){const frame=el('div','application-qr-frame');frame.append(qrImage('application-qr',display),el('p','application-qr-caption','Scan to apply'));slide.append(frame)}else console.warn('Application QR hidden because the published website URL differs from the QR target.',url);slide.dataset.focus='application';return slide}
function overviewSlide(text,cities,courses){const slide=el('section','slide overview'),copy=el('div','overview-copy'),title=el('h1');title.append(el('span','overview-line-one',text.hero_line_1||fallbackText.hero_line_1),el('span','overview-line-two',text.hero_line_2||fallbackText.hero_line_2));const description=el('p','overview-description'),program=el('strong','',`The ${text.program_title}`);description.append(program,document.createTextNode(` ${text.intro_sentence_1||fallbackText.intro_sentence_1} ${text.intro_sentence_2||fallbackText.intro_sentence_2} `),el('strong','',`${text.program_term}.`));copy.append(title,description);const stats=el('div','overview-stats');[[cities.length,'cities'],[new Set(cities.map(c=>c.country)).size,'countries'],[courses.length,'courses']].forEach(([number,label])=>{const box=el('div');box.append(el('strong','',number),el('span','',label));stats.append(box)});slide.append(copy,stats);slide.dataset.focus='europe';return slide}
function curriculumSlide(text,courses){const slide=el('section','slide curriculum-slide'),heading=el('div','curriculum-heading'),title=el('h1');title.append(document.createTextNode('Make the summer '),el('span','', 'count'));heading.append(el('p','eyebrow',text.courses_heading||'Four courses in global affairs'),title);const list=el('ol','curriculum-courses');courses.forEach(course=>{const item=el('li'),name=el('strong','',course.Course||course.title),code=el('span','',course.Code||course.code);item.append(name,code);list.append(item)});const credentials=el('div','curriculum-credentials');[[text.certificate_title||'Earn a Certificate in European Studies',text.certificate_detail||"with the program's four courses"],[text.minor_title||'Complete the International Affairs minor',text.minor_detail||'with the program plus one additional course']].forEach(([name,detail])=>{const item=el('div','curriculum-credential');item.append(el('strong','',name),el('span','',detail));credentials.append(item)});slide.append(heading,list,credentials);slide.dataset.focus='curriculum';return slide}
function portraitFor(link=''){const key=Object.keys(facultyPhotos).find(part=>link.includes(part));return facultyPhotos[key]||''}
function facultySlide(person){const slide=el('section','slide faculty-slide'),copy=el('div','faculty-copy');copy.append(el('p','eyebrow','Featured faculty'),el('div','rule'),el('h1','',person.Name),el('p','faculty-role',person['Program Title']||'Program faculty'));const link=el('a','faculty-link','View Georgia Tech profile');link.href=person.Link;link.target='_blank';link.rel='noreferrer';link.addEventListener('click',event=>event.stopPropagation());copy.append(link);const image=el('img','faculty-photo'),positionKey=Object.keys(facultyPositions).find(part=>person.Link.includes(part));image.src=portraitFor(person.Link);image.alt=person.Name;image.style.objectPosition=facultyPositions[positionKey]||'center 35%';slide.append(copy,image);slide.dataset.focus='faculty';return slide}
function facultyGroupSlide(people){const slide=el('section','slide faculty-group-slide'),heading=el('div','faculty-group-heading'),grid=el('div','faculty-group-grid');heading.append(el('p','eyebrow','Program faculty'),el('h1','','Meet your faculty'));people.forEach(person=>{const card=el('a','faculty-card'),image=el('img'),name=el('strong','',person.Name),role=el('span','',person['Program Title']||'Program faculty');card.href=person.Link;card.target='_blank';card.rel='noreferrer';card.addEventListener('click',event=>event.stopPropagation());image.src=portraitFor(person.Link);image.alt='';const positionKey=Object.keys(facultyPositions).find(part=>person.Link.includes(part));image.style.objectPosition=facultyPositions[positionKey]||'center 35%';card.append(image,name,role);grid.append(card)});slide.append(heading,grid);slide.dataset.focus='faculty';return slide}
function gallerySlide(){const slide=el('section','slide gallery-slide'),copy=el('div','gallery-copy'),title=el('h1');title.append(document.createTextNode('Picture yourself '),el('span','', 'in Europe'));const description=el('p','', 'Study, travel, and build a community across Europe. These moments come from the 2023 and 2024 programs.');const link=el('a','gallery-link','Explore the full student gallery');link.href=galleryUrl;link.target='_blank';link.rel='noreferrer';link.addEventListener('click',event=>event.stopPropagation());copy.append(el('p','eyebrow','Student experience'),title,description,link);const grid=el('div','gallery-grid');galleryPhotos.forEach(([src,alt])=>{const image=el('img');image.src=src;image.alt=alt;grid.append(image)});slide.append(copy,grid);slide.dataset.focus='gallery';return slide}
function citySlide(city,index,records){const slug=citySlugs[city.city]||city.city.toLowerCase().replaceAll(' ','-'),cityPhotos=records.filter(r=>r.city===slug&&r.role==='city'),slide=el('section','slide city-slide');const image=el('img','city-photo'),hero=cityPhotos[index%Math.max(cityPhotos.length,1)]||records.find(r=>r.city===slug);if(hero)image.src=`photos/${slug}/${hero.file}`;image.alt=`${city.city}, ${city.country}`;const copy=el('div','city-copy'),label=(city.category||'').toLowerCase()==='basecamp'?'Basecamp':'Featured excursion';copy.append(el('p','city-index',label),el('h1','',city.city),el('p','country',city.country));slide.append(image,el('div','city-photo-shade'),copy);slide.dataset.focus='city';slide.dataset.city=city.city;return slide}
function siteSlide(site){const slide=el('section','slide site-slide'),image=el('img','site-photo'),copy=el('div','site-copy');copy.append(el('p','site-index','Featured site visit'),el('div','site-rule'),el('h1','site-name'),el('p','site-location'));slide.append(image,el('div','site-gold-panel'),copy,el('p','site-photo-caption'));slide.dataset.focus='site';updateSiteSlide(slide,site);return slide}
function updateSiteSlide(slide,site){slide.querySelector('.site-photo').src=site.photo;slide.querySelector('.site-photo').alt=`${site.institution}, ${site.city}, ${site.country}`;slide.querySelector('.site-name').textContent=site.institution;slide.querySelector('.site-location').textContent=`${site.city}, ${site.country}`;slide.querySelector('.site-photo-caption').textContent=site.photo_caption||'';slide.dataset.institution=site.institution;slide.dataset.city=site.city}

const globeState={lon:10,lat:49,targetLon:10,targetLat:49,activeCity:null,cities:[],topology:null,last:0};
function decodeArc(topology,index){const reversed=index<0,arc=topology.arcs[reversed?~index:index],scale=topology.transform?.scale||[1,1],translate=topology.transform?.translate||[0,0];let x=0,y=0;const points=arc.map(pair=>{x+=pair[0];y+=pair[1];return[x*scale[0]+translate[0],y*scale[1]+translate[1]]});return reversed?points.reverse():points}
function geometryRings(topology,geometry){const polygon=rings=>rings.map(ring=>ring.flatMap((arcIndex,i)=>{const points=decodeArc(topology,arcIndex);return i?points.slice(1):points}));if(geometry.type==='Polygon')return[polygon(geometry.arcs)];if(geometry.type==='MultiPolygon')return geometry.arcs.map(polygon);return[]}
function globeProjection(width,height){const lon0=globeState.lon*Math.PI/180,lat0=globeState.lat*Math.PI/180,perspective=1.42,distance=1+1/perspective,cutoff=1/distance,isCity=slides[current]?.dataset.focus==='city',cx=width*(isCity?.79:.77),cy=height*(isCity?.69:.67),radius=Math.min(width,height)*2.15,horizon=Math.sqrt((distance-1)/(distance+1));const project=([lonDeg,latDeg])=>{const lon=lonDeg*Math.PI/180,lat=latDeg*Math.PI/180,dl=lon-lon0,rawX=Math.cos(lat)*Math.sin(dl),rawY=Math.cos(lat0)*Math.sin(lat)-Math.sin(lat0)*Math.cos(lat)*Math.cos(dl),z=Math.sin(lat0)*Math.sin(lat)+Math.cos(lat0)*Math.cos(lat)*Math.cos(dl),factor=(distance-1)/(distance-z);return[cx+radius*rawX*factor,cy-radius*rawY*factor,z-cutoff]};return{project,cx,cy,radius:radius*horizon}}
function trace(ctx,ring,project){let drawing=false;for(const point of ring){const[x,y,z]=project(point);if(z<=.01){drawing=false;continue}if(!drawing){ctx.moveTo(x,y);drawing=true}else ctx.lineTo(x,y)}}
function drawGlobe(){const canvas=document.querySelector('#globe');if(!globeState.topology)return;const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),width=rect.width,height=rect.height;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);const {project,cx,cy,radius}=globeProjection(width,height);ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.fillStyle='#f1f0eb';ctx.fill();ctx.strokeStyle='rgba(5,30,57,.65)';ctx.lineWidth=1.2;ctx.stroke();ctx.save();ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.clip();ctx.strokeStyle='rgba(5,30,57,.11)';ctx.lineWidth=.7;for(let lon=-180;lon<180;lon+=15){ctx.beginPath();let started=false;for(let lat=-80;lat<=80;lat+=2){const[x,y,z]=project([lon,lat]);if(z<=0){started=false;continue}started?ctx.lineTo(x,y):(ctx.moveTo(x,y),started=true)}ctx.stroke()}for(let lat=-75;lat<=75;lat+=15){ctx.beginPath();let started=false;for(let lon=-180;lon<=180;lon+=2){const[x,y,z]=project([lon,lat]);if(z<=0){started=false;continue}started?ctx.lineTo(x,y):(ctx.moveTo(x,y),started=true)}ctx.stroke()}for(const geometry of globeState.topology.objects.countries.geometries)for(const polygon of geometryRings(globeState.topology,geometry)){ctx.beginPath();polygon.forEach(ring=>trace(ctx,ring,project));ctx.fillStyle='#e6e5df';ctx.fill('evenodd');ctx.strokeStyle='rgba(25,25,25,.48)';ctx.lineWidth=.65;ctx.stroke()}globeState.cities.forEach(city=>{const[x,y,z]=project([city.lon,city.lat]);if(z<=0)return;const active=globeState.activeCity===city.city,home=!presentationMode&&slides[current]?.classList.contains('overview');ctx.beginPath();ctx.arc(x,y,active?9:home?10:4.8,0,Math.PI*2);ctx.fillStyle='#b39051';ctx.fill();ctx.strokeStyle=active?'#051e39':'#fff';ctx.lineWidth=active?2.2:home?1.8:1.1;ctx.stroke();if(active){ctx.beginPath();ctx.arc(x,y,17,0,Math.PI*2);ctx.strokeStyle='rgba(179,144,81,.6)';ctx.lineWidth=2;ctx.stroke()}});ctx.restore();window.__EUGA_BANNER_READY__=true}
function animate(time){const delta=Math.min(40,time-(globeState.last||time));globeState.last=time;const dLon=((globeState.targetLon-globeState.lon+540)%360)-180,dLat=globeState.targetLat-globeState.lat,ease=1-Math.pow(.86,delta/16.67);globeState.lon+=dLon*ease;globeState.lat+=dLat*ease;drawGlobe();requestAnimationFrame(animate)}

let slides=[],current=0,sitePool=[],siteSlots=[];
let autoplayTimer=null;
function shuffled(values){const result=[...values];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
function rotateSiteSlots(){if(presentationMode||!siteSlots.length||!sitePool.length)return;const shown=new Set(siteSlots.map(slide=>slide.dataset.institution)),unused=sitePool.filter(site=>!shown.has(site.institution)),next=shuffled(unused.length>=siteSlots.length?unused:sitePool).slice(0,siteSlots.length);siteSlots.forEach((slide,index)=>updateSiteSlide(slide,next[index]))}
function setGlobeTarget(slide){const city=globeState.cities.find(item=>item.city===slide.dataset.city);if(city){globeState.targetLon=city.lon;globeState.targetLat=city.lat;globeState.activeCity=city.city}else{globeState.targetLon=10;globeState.targetLat=49;globeState.activeCity=null}}
function renderProgress(){const progress=document.querySelector('#progress-dots');progress.replaceChildren(...slides.map((slide,index)=>{const dot=el('button','progress-dot');dot.type='button';dot.setAttribute('aria-label',`Go to slide ${index+1}`);dot.addEventListener('click',event=>{event.stopPropagation();show(index);restartAutoplay()});return dot}))}
function show(index){if(current===slides.length-1&&index===0)rotateSiteSlots();current=Math.max(0,Math.min(index,slides.length-1));slides.forEach((slide,i)=>slide.classList.toggle('is-active',i===current));document.querySelectorAll('.progress-dot').forEach((dot,i)=>dot.classList.toggle('is-active',i===current));document.documentElement.dataset.slideFocus=slides[current].dataset.focus||'';setGlobeTarget(slides[current]);document.querySelector('#previous').disabled=current===0;document.querySelector('#next').disabled=current===slides.length-1;const nextParams=new URLSearchParams(location.search);nextParams.set('slide',current+1);history.replaceState(null,'',`${location.pathname}?${nextParams}`)}
function advance(amount=1){show((current+amount+slides.length)%slides.length);restartAutoplay()}
function restartAutoplay(){if(!autoplayMode)return;clearInterval(autoplayTimer);autoplayTimer=setInterval(()=>{if(!document.hidden)show((current+1)%slides.length)},8000)}
async function init(){
  let text={...fallbackText},cities=[],courses=[],faculty=fallbackFaculty,photos=[],institutions=[];
  const [fallback,manifest]=await Promise.all([fetch('data/program.json').then(r=>r.json()),presentationMode?Promise.resolve([]):fetch('data/institutions.json').then(r=>r.json())]);
  try{
    const [textRows,cityRows,courseRows,facultyRows,institutionRows,photoResponse,topology]=await Promise.all([sheet(gids.text),sheet(gids.cities),sheet(gids.courses),sheet(gids.faculty),presentationMode?Promise.resolve([]):sheet(gids.institutions),fetch('photos/sources.json'),fetch('assets/countries-110m.json').then(r=>r.json())]);
    text={...text,...Object.fromEntries(textRows.filter(r=>r.Key).map(r=>[r.Key,r.Value]))};
    const coordinates=new Map(fallback.cities.map(c=>[c.city.toLowerCase(),c]));
    cities=cityRows.map(row=>({...coordinates.get((row.City||'').toLowerCase()),city:row.City,country:row.Country,category:row.Category})).filter(city=>city.city&&Number.isFinite(city.lon));
    courses=courseRows;faculty=facultyRows.filter(row=>row.Name&&row.Link);photos=await photoResponse.json();globeState.topology=topology;
    const media=new Map(manifest.map(site=>[site.institution,site]));
    institutions=institutionRows.filter(row=>row.Institution&&row.City&&row.Country).map(row=>({institution:row.Institution,city:row.City,country:row.Country,photo:media.get(row.Institution)?.photo,photo_caption:media.get(row.Institution)?.photo_caption}));
    document.documentElement.dataset.contentSource='sheet';
  }catch(error){
    console.warn('Using local content fallback.',error);cities=fallback.cities;courses=fallback.courses;institutions=manifest;photos=await fetch('photos/sources.json').then(r=>r.json());globeState.topology=await fetch('assets/countries-110m.json').then(r=>r.json());document.documentElement.dataset.contentSource='fallback';
  }
  const available=presentationMode?[]:await Promise.all(institutions.map(async site=>site.photo&&await fetch(site.photo,{method:'HEAD'}).then(response=>response.ok).catch(()=>false)?site:null));
  sitePool=available.filter(Boolean);
  document.documentElement.dataset.institutionCount=institutions.length;
  document.documentElement.dataset.institutionPhotoCount=sitePool.length;
  if(sitePool.length!==institutions.length)console.warn('Institution photos awaiting verification:',institutions.filter(site=>!sitePool.includes(site)).map(site=>site.institution));
  globeState.cities=cities;
  const allBasecamps=cities.filter(city=>(city.category||'').toLowerCase()==='basecamp'),allExcursions=cities.filter(city=>(city.category||'').toLowerCase()!=='basecamp'),deck=document.querySelector('#deck');
  if(presentationMode){
    slides=[openingSlide(text),overviewSlide(text,cities,courses),curriculumSlide(text,courses),facultyGroupSlide(faculty),gallerySlide(),...allBasecamps.map((city,i)=>citySlide(city,i,photos)),...allExcursions.map((city,i)=>citySlide(city,i,photos)),applicationSlide(text)];
  }else{
    const basecamps=shuffled(allBasecamps).slice(0,2),excursions=shuffled(allExcursions).slice(0,2),featuredFaculty=shuffled(faculty).slice(0,Math.min(2,faculty.length));
    siteSlots=shuffled(sitePool).slice(0,2).map(siteSlide);
    slides=[overviewSlide(text,cities,courses),citySlide(basecamps[0],0,photos),...(featuredFaculty[0]?[facultySlide(featuredFaculty[0])]:[]),citySlide(excursions[0],0,photos),...(siteSlots[0]?[siteSlots[0]]:[]),curriculumSlide(text,courses),citySlide(basecamps[1],1,photos),...(featuredFaculty[1]?[facultySlide(featuredFaculty[1])]:[]),gallerySlide(),citySlide(excursions[1],1,photos),...(siteSlots[1]?[siteSlots[1]]:[])];
  }
  if(presentationMode)slides.forEach(slide=>{if(!slide.classList.contains('opening')&&!slide.classList.contains('application-slide'))slide.append(programBrand())});
  deck.append(...slides);renderProgress();const requested=Number(params.get('slide'));show(Number.isFinite(requested)&&requested>0?requested-1:0);requestAnimationFrame(animate);restartAutoplay();
}
document.querySelector('#previous').addEventListener('click',event=>{event.stopPropagation();advance(-1)});document.querySelector('#next').addEventListener('click',event=>{event.stopPropagation();advance(1)});document.querySelector('#deck').addEventListener('click',()=>advance(1));document.addEventListener('keydown',event=>{if(['ArrowRight',' ','PageDown'].includes(event.key)){event.preventDefault();advance(1)}if(['ArrowLeft','PageUp'].includes(event.key)){event.preventDefault();advance(-1)}if(event.key==='Home'){show(0);restartAutoplay()}if(event.key==='End'){show(slides.length-1);restartAutoplay()}});window.addEventListener('resize',drawGlobe);init();
